version: '3.8'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT_EXPORTED}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    networks:
      - tech-demo
    command: ['mysqld']

  api:
    image: foundation/tech-demo-api:latest
    build:
      dockerfile: Dockerfile
      args:
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        - ADMIN_PASS=${ADMIN_PASS}
        - PLAYWRIGHT_SLOW_MO=${PLAYWRIGHT_SLOW_MO}
    ports:
      - ${API_PORT_EXPORTED}:8080
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tech-demo
      - SPRING_DATASOURCE_USERNAME=${MYSQL_DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_DATABASE_PASSWORD}
    networks:
      - tech-demo

volumes:
  mysql-data:
networks:
  tech-demo: